### ISSUE TITLE
Action trigger on Cover Click/Tap

### ISSUE THREAD

**Issue by gaga191281** [punxaphil/custom-sonos-card#298]
It would be very convenient to be able to trigger a action (service call for instance) when taping or clicking on a cover.
This would make it possible for example to open the Sonos App when clicking on the cover. Instead of creating a extra button for it.

**Comment by punxaphil** [comment]
Why do you need the Sonos app?

**Comment by gaga191281** [comment]
When searching for a specific song or browsing thorough my Playlists and so

**Comment by punxaphil** [comment]
You won't be able to open a specific playlist with such a service call though. Our focus on search in the app.
I'm not sure this feature fits in the scope of this card. I recommend you just adding a button for it.

**Comment by gaga191281** [comment]
I think you got me wrong. The idea is to trigger a service call that simply opens the native Sonos App. There I am able to do everything

**Comment by punxaphil** [comment]
I'm still not sure this feature fits in the scope of this card. I recommend you just adding a button for it.

**Comment by motoridersd** [comment]
I would like to bump this as a request. I can think of a few use cases for a click action that don't necessarily involve the Sonos app. It could be used to hide buttons at the bottom so that for example a click action opens the Groups, or triggers the Next action (that way we can hide the control buttons). The tap, hold and double tap actions could be used to trigger a lot of different things from the Sonos card to make dashboards cleaner.

**Comment by punxaphil** [comment]
Feel free to contribute to the code through a pull request

**Comment by Vansmak** [comment]
Or just the ability to add shortcuts or make favorite more dynamic, a favorite that is a tap action, call service etc.
