### ISSUE TITLE
artwork - size increased a few commits ago?

### ISSUE THREAD

**Issue by Symbiot78** [punxaphil/custom-sonos-card#317]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
7.3.0
**Last working release (if known):**
2-4 versions back
**Browser and Operating System:**
opera/silk/edge
windows 11 + amazon echo
**Description of problem:**

artwork seems to have increased in size - usually the card fits and my guess is that the artwork resized itself to fit the boundaries of the card.. but I may be wrong. I have NOT set any config to change the artwork size.

Tell me if there's more you need.. I'll do my best to provide it.

![image](https://github.com/punxaphil/custom-sonos-card/assets/3314249/385dc0a6-5000-4441-a3a4-54cf2ecebc90)

**Comment by punxaphil** [comment]
Yeah, I had to add min-height to the artwork, since it disappeared fully otherwise for those users that wanted the card to adjust its height using auto. 
I have reduced min-height now to 5rem by default. You can change it further with `artworkMinHeight`.
Try it here: https://github.com/punxaphil/custom-sonos-card/releases/tag/v7.4.0

**Comment by Symbiot78** [comment]
@punxaphil  - you Sir, are a beautiful young <insert gender> :)

**Comment by punxaphil** [comment]
> @punxaphil - you Sir, are a beautiful young :)

Thanks 🤩 
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
