### ISSUE TITLE
Main volume controller shows group volume 

### ISSUE THREAD

**Issue by ecser99** [punxaphil/custom-sonos-card#350]
Hi,
I activate this option:

playerVolumeOnlyAffectsMainPlayer: true

and group another player to the dedicated player and change the main volume.

Result:
The volume controller change the dedicated player's volume (this is OK) but it shows the group volume (this is wrong).
The volume contreoller should change and show the dedicated player's volume.

version: 7.10
https://github.com/punxaphil/custom-sonos-card/issues/327

Thanx!

**Comment by punxaphil** [comment]
`playerVolumeOnlyAffectsMainPlayer` was replaced by:
`playerVolumeEntityId: media_player.bedroom # default is empty. Use this to control the volume of another player in the player section. Entity ID must the selected player or part of the selected player's group, otherwise it will not be controlled.`

**Comment by ecser99** [comment]
Great!
Thank you!
