### ISSUE TITLE
Highlight color for buttons: shuffle, repeat and mute 

### ISSUE THREAD

**Issue by ecser99** [punxaphil/custom-sonos-card#405]
**Is your feature request related to a problem? Please describe.**
It is not easy to visually identify, if these buttons are active or not.

**Describe the solution you'd like**
When these buttons are in an active state, the buttons shold be higlighted with the actual highlight color (in this example light blue).
See the picture below (buttons marked with red).

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/punxaphil/custom-sonos-card/assets/10208264/64141af2-c985-49cb-a330-3e090fe41bf2)

For the mute button I reccommend this for the **inactive state**:
![image](https://github.com/punxaphil/custom-sonos-card/assets/10208264/6aee4562-d7f5-4519-bee3-d9976a61ed57)
And for **active mute** I recommend the same icon highlighted.

Now the mute button is this:
![image](https://github.com/punxaphil/custom-sonos-card/assets/10208264/2e3c6415-2e15-4bf2-863f-5dbdc94e8453)
but it does not really tell the user, what it is. It would be better to have a mute button with the "x" and highlight it when activ.

**Comment by punxaphil** [comment]
These parts are actually from Home Assistant core, so Sonos Card is just reusing those. As you see if you use the built in media player, they look the same. Because of that I am afraid I have to reject this request. Feel free to ask Home Assistant core to change their styling, then it will be applied in this card as well.
